version: "3"
services: 
  backend:
    build: ./backend
    image: be-organize-matches:latest
    container_name: be-organize-matches
    restart: on-failure
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    image: fe-organize-matches:latest
    container_name: fe-organize-matches
    restart: on-failure
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      REACT_APP_API_HOST: localhost:8081

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/