spring:
  main:
    banner-mode: 'off'
  data:
    mongodb:
      database: organize-matches
      uri: mongodb://root:orgmatches@localhost:27017/admin?authMechanism=SCRAM-SHA-256

server:
  port: 8081