spring:
  main:
    banner-mode: 'off'
  data:
    mongodb:
      database: organize-matches
      auto-index-creation: true

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: organize-matches-dev
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: organize-matches